name: instagram
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.4.0
  bloc: ^8.1.2
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  freezed: ^2.1.0+1
  get_it: ^7.6.0
  image_picker: ^1.0.1
  intl: ^0.18.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.2
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.2.0
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
